language: node_js
cache:
  - node_modules
  - bundler

before_install:
  - rvm use $(< .ruby-version) --install --binary --fuzzy
  - sudo apt-get update -qq
  - sudo apt-get install -qq optipng libjpeg-progs
install:
  - npm install
  - bundle install

before_script:
  - env
script: ./bin/deploy

env:
  global:
    - PREFIX_FOLDER=$([ "$TRAVIS_PULL_REQUEST" != "false" ] && echo "pr-$TRAVIS_PULL_REQUEST")
    - APP_URL=$([ "$TRAVIS_TAG" != "" ] && echo "https://app.honeypot.io" || echo "https://staging.honeypot.io")
    - URL_BASE=$([ "$PREFIX_FOLDER" != "" ] && echo "/$PREFIX_FOLDER")
