language: node_js

install:
  - npm install
  - bundle install

before_script:
  - env
script: ./bin/deploy

env:
  global:
    - PREFIX_FOLDER=$([ "$TRAVIS_PULL_REQUEST" != "false" ] && echo "pr-$TRAVIS_PULL_REQUEST")
