language: node_js
cache:
  directories:
    - node_modules
    - bundler
before_install:
  - ruby --version
install:
  - npm install node-smushit -g
  - npm install
  - bundle install
script: travis_wait ./bin/deploy

env:
  global:
    - PREFIX_FOLDER=$([ "$TRAVIS_PULL_REQUEST" != "false" ] && echo "pr-$TRAVIS_PULL_REQUEST")
    - APP_HOST=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_APP_HOST" || echo "$STAGING_APP_HOST")
    - API_HOST=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_API_HOST" || echo "$STAGING_API_HOST")
    - URL_BASE=$([ "$PREFIX_FOLDER" != "" ] && echo "/$PREFIX_FOLDER")
    - GTM_ID=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_GTM_ID" || echo "$STAGING_GTM_ID")
    - GA_ID=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_GA_ID" || echo "$STAGING_GA_ID")
    - S3_FORCE=$(git log -1 --pretty=%B | grep -E "^\[#s3 .*force.*]" --ignore-case)
    - S3_CFG=$(git log -1 --pretty=%B | grep -E "^\[#s3 .*(cfg|config|configure).*]" --ignore-case)
