language: node_js
cache:
  directories:
    - node_modules
    - bundler
before_install:
  - rvm use $(< .ruby-version) --install --binary --fuzzy
install:
  - npm install node-smushit -g
  - npm install
  - bundle install
before_script:
  - env
script: travis_wait ./bin/deploy

env:
  global:
    - PREFIX_FOLDER=$([ "$TRAVIS_PULL_REQUEST" != "false" ] && echo "pr-$TRAVIS_PULL_REQUEST")
    - APP_URL=$([ "$TRAVIS_TAG" != "" ] && echo "https://app.honeypot.io" || echo "https://staging.honeypot.io")
    - URL_BASE=$([ "$PREFIX_FOLDER" != "" ] && echo "/$PREFIX_FOLDER")
    - GTM_ID=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_GTM_ID" || echo "$STAGING_GTM_ID")
    - GA_ID=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_GA_ID" || echo "$STAGING_GA_ID")
