#!/usr/bin/env ruby
require 'fileutils'

class VendorCopy
  PATHS=%w{
    bootstrap-sass/assets/javascripts/bootstrap.js
    picturefill/dist/picturefill.js
    jquery-cookiebar/jquery.cookiebar.js
  }
  NPM_DIR='node_modules/'
  DESTINATION_DIR='vendor/'

  def self.call
    FileUtils.mkdir_p(DESTINATION_DIR)
    PATHS.each do |path|
      FileUtils.cp(NPM_DIR + path, DESTINATION_DIR)
    end
  end
end

VendorCopy.call if __FILE__ == $0
